services:
  db:
    image: ankane/pgvector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rfp_db
      POSTGRES_PASSWORD: password
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"